Added MatchingRules for Tweet
Xwilarg/TwitterSharp pull request #17
Opened 2022-02-04 14:08 UTC by marcogruhl

Added MatchingRules for Tweet
Extend Examples with Matching Rules
Added Author Every3Minutes to examples because it tweets every 3 minutes
Corrected comment

2022-02-04 14:14 UTC, Xwilarg requested changes

2022-02-04 14:14 UTC, Xwilarg commented on src/Client/TwitterClient.cs
> +        }
```suggestion
        }
```

2022-02-04 14:14 UTC, Xwilarg commented on README.md
> +         Console.WriteLine($"From {tweet.Author.Name}: {tweet.Text} (Rules: {string.Join(',', tweet.MatchingRules.Select(x => x.Tag))})");
Is the empty space added normal?

2022-02-04 14:14 UTC, Xwilarg commented on src/Response/Answer.cs
> +    public class MatchingRule
Shouldn't this be internal?

2022-02-04 14:14 UTC, Xwilarg commented on src/Client/TwitterClient.cs
> +                if (answer.MatchingRules != null && answer.MatchingRules.Length > 0 && _matchingRulesInterface.IsAssignableFrom(typeof(T)))
.Length > 0 can be replaced by .Any()

2022-02-04 14:20 UTC, Xwilarg requested changes

2022-02-04 14:20 UTC, Xwilarg commented on README.md
>              Expression.Author("watsonameliaEN")
This is correct per see but I feel like the mix between anime vtubers and slavery is a bit strange, maybe make it a separate rule?

2022-02-04 14:31 UTC, marcogruhl commented on README.md
>              Expression.Author("watsonameliaEN")
good point. I thought you chose them for a high tweet rate 😅. I check if a separate rule makes sense in the sample context. Or i will completely remove it.

2022-02-04 14:37 UTC, marcogruhl commented on README.md
> +         Console.WriteLine($"From {tweet.Author.Name}: {tweet.Text} (Rules: {string.Join(',', tweet.MatchingRules.Select(x => x.Tag))})");
Overseen this. IDE works not that well with md files. Will be fixed.

2022-02-04 14:56 UTC, marcogruhl commented on src/Response/Answer.cs
> +    public class MatchingRule
The type is used at Tweet.cs L83 as normal property. I could separate an internal and public Type. Don't know if that makes sense. I am not 100% aware of that. Folowed mostly your patterns.

2022-02-04 14:57 UTC, marcogruhl commented on src/Client/TwitterClient.cs
> +                if (answer.MatchingRules != null && answer.MatchingRules.Length > 0 && _matchingRulesInterface.IsAssignableFrom(typeof(T)))
Changed that. Copy pasted it from your code 😉

2022-02-04 14:58 UTC, Xwilarg commented on src/Response/Answer.cs
> +    public class MatchingRule
Ah my bad, didn't read properly, mayble make it a record instead of a class since it's immutable then?

2022-02-04 15:08 UTC, marcogruhl commented on src/Response/Answer.cs
> +    public class MatchingRule
Or I make it a "normal" separate file like Attachments.cs and remove it from the answer file? And also make it a record ...

2022-02-04 15:09 UTC, Xwilarg commented on src/Response/Answer.cs
> +    public class MatchingRule
Yeah I think it would be more logic

2022-02-05 09:54 UTC, Xwilarg requested changes

2022-02-05 09:54 UTC, Xwilarg commented on src/Response/RTweet/MatchingRule.cs
> +        public string Tag { init; get; }
init specifier can be internal I think

2022-02-06 00:58 UTC, marcogruhl commented on src/Response/RTweet/MatchingRule.cs
> +        public string Tag { init; get; }
It does not work. Tested it, and the values were empty. Don't know why. Maybe the deserialization works some kind of outside the assembly?

2022-02-06 00:59 UTC, Xwilarg commented on src/Response/RTweet/MatchingRule.cs
> +        public string Tag { init; get; }
Ah yup, that's possible

2022-02-06 12:29 UTC, Xwilarg approved these changes

2022-02-06 12:29 UTC, merged

2022-02-06 12:37 UTC, Xwilarg commented
https://www.nuget.org/packages/TwitterSharp/1.4.0