Rate limit endpoint enum
Xwilarg/TwitterSharp pull request #19
Opened 2022-02-12 02:44 UTC by marcogruhl

All Endpoints decorated with
- Description
- Rate Limits (per App/User, reset Time)
- Counts against the Tweet Cap
- max operations limits
And also Endpoint relevant information
- Endpoint Type
- Endpoint Url
- Access Level

This information will help to get relations between these properties. 

All information are carried together from:
[Twitter API v2](https://developer.twitter.com/en/docs/twitter-api)
[Developer Portal - Products](https://developer.twitter.com/en/portal/products/)
[Rate limits](https://developer.twitter.com/en/docs/twitter-api/rate-limits)

2022-02-12 02:54 UTC, Xwilarg requested changes

2022-02-12 02:54 UTC, Xwilarg commented on src/Response/RRateLimit/AccessLevel.cs
> +    public enum AccessLevel
You may want to use the [Flag](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-6.0) attribute on that

2022-02-14 00:29 UTC, marcogruhl commented on src/Response/RRateLimit/AccessLevel.cs
> +    public enum AccessLevel
Don't know about that - changed it

2022-02-14 00:33 UTC, marcogruhl commented
I also optimized the Namespaces. Now i it suits better. I cant name the Endpoint-"Folder" "Endpoint" because it collides with the enum Name. So ApiEndpoint was my solution to that.

2022-02-14 08:38 UTC, Xwilarg requested changes

2022-02-14 12:14 UTC, marcogruhl commented on src/Response/RateLimit.cs
> +namespace TwitterSharp.Response.RRateLimit
sorry, i missed that - fixed
the refactoring also found a "wrong" namespace in answer.cs ... refactored that too ... please verify

2022-02-15 12:32 UTC, Xwilarg approved these changes

2022-02-15 12:33 UTC, merged