Error handling
Xwilarg/TwitterSharp pull request #31
Opened 2022-07-02 09:22 UTC by marcogruhl

handle errors with an exception.
Extended Answer and TwitterException object.

Could you please review if the logic is suitable? I don't like the exception approach, but it is non breaking and simple. As alternative I can imaging some base class for all response objects and parsing like:

```C#
private T[] ParseArrayData<T>(string json) where T : IHaveError
```

I will add some Test this weekend. I couldn't find an exact structure of the `Error` object. I (for now) could only produce errors with an detail**S** property but in the docs i see only a detail property.

I pushed this to discuss these points.

2022-07-03 02:36 UTC, Xwilarg commented
Hey, sorry for the late answer, improving the error handling is definitly a great idea!

But yeah maybe instead it would be better to have many kind of exception instead of having the type as a variable inside?

2022-07-03 17:20 UTC, marcogruhl commented
I would like to implement as exact as possible, but i couldn't find docs for the error responses. This is the main doc i used: [Errors](https://developer.twitter.com/en/support/twitter-api/error-troubleshooting). For some endpoints there are examples for the error response like [filtered-stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/consuming-streaming-data) but only for the fewest. So my implementation is as general as possible:
title, detail, type and errors. In the errors object there are also message, title and type along with details as default and i extend it with parameter/s code and value.
The integration in the Parse method is more like extending the existing `answer.Detail != null` and like i said, non breaking.

I think this is all i can do for now.

2022-07-03 23:19 UTC, Xwilarg commented
Uhm yeah I indeed think it's a good idea

2022-07-04 14:24 UTC, marcogruhl commented
> Uhm yeah I indeed think it's a good idea

sorry I dont understand, what is a good idea?

I just wanted to say: I cant do better for now.

2022-07-04 14:28 UTC, Xwilarg commented
I meant what you are currently doing, I'll check the code more in details in the following days

2022-07-04 14:39 UTC, marcogruhl commented
Thank you! No hurry! I can carry on with my depending project!

2022-07-07 07:19 UTC, Xwilarg requested changes

2022-07-07 07:19 UTC, Xwilarg commented on src/Client/TwitterClient.cs
> +                throw new TwitterException(answer.Detail ?? "Error. See Errors property.", answer.Title, answer.Type ?? "Error", answer.Errors);
Maybe all these checks should be moved to the ctor of TwitterException instead?

2022-07-08 10:24 UTC, Xwilarg commented
Hey, should I merge this PR or are you still busy with it?

2022-07-08 10:50 UTC, marcogruhl commented
You can merge it. Work is done.

2022-07-08 12:41 UTC, merged