StringToExpression and Expression Tree
Xwilarg/TwitterSharp pull request #39
Opened 2022-09-07 01:23 UTC by marcogruhl

### Features

- Expressions extended with Type
- Expressions extended with tree (for And and Or)
- Add Expressions: FollowersCount, TweetsCount, FollowingCount, ListedCount, UrlTitle, UrlDescription, UrlContains, Source, InReplyToTweetId, RetweetsOfTweetId
- Parse Expression from String

### Fixes

- Faulty expression test excepted "xx" as country -> "xxxx"
- Entity had wrong space

### Extended

- prevent double negation
- prevent IsNotNullcast negation
- prevent double double-quotes

2022-09-07 01:31 UTC, Xwilarg commented
Thanks for all your work! I'll have a closer look and test this tomorrow then come back to you

2022-09-07 13:25 UTC, Xwilarg commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
In what case would that throw an exception? I feel like catching everything and discarding the exception could be dangerous...

2022-09-07 13:27 UTC, Xwilarg commented
Also could you please fix the Codacy issues and maybe add an example in the README about the expressions?

2022-09-07 13:39 UTC, marcogruhl commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
Its a simple fallback if something goes wrong in the paring of the string. Even if its not my fault, e.g. something changed on the api. any ideas to handle it better?

2022-09-07 13:41 UTC, Xwilarg commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
Well in the case of something changing in the API I think it would be better to just rethrow so we could be aware of it and fix it

2022-09-07 13:41 UTC, marcogruhl commented
> Also could you please fix the Codacy issues

there are ~50 one liner which will add ~100 lines of brackets ... but for the bless of Codacy 😅 ... I had no hard feelings about. Will do ...

> and maybe add an example in the README about the expressions?

Good point. I will do.

2022-09-07 13:44 UTC, Xwilarg commented
Ah no yeah it's okay about the brackets, I was more thinking of the others ones

2022-09-07 14:21 UTC, marcogruhl commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
I am afraid of breaking some existing software, because it is "just a feature" no one is using for now and we could not test every case by definition (academic licence)! If we throw an exception the users are damned to use this feature correctly.
And if something goes wrong it breaks the JsonConverter which is in our hands and the user had no access to.

I can think of handling it within the ToExpression method express something like "HasErrors" or "HasParsingErrors" or/and rename it to TryParse ... so its less "demanding" 😬

2022-09-07 14:28 UTC, Xwilarg commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
Yeah maybe doing a TryParse and keeping unit tests could be a solution?

2022-09-07 14:32 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
You are already in the static class so you can remove all the "Expression."

2022-09-07 14:32 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
You can replace sr.Substring(1) by sr[1..]

2022-09-07 14:33 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                            case "followers_count:": AddExpression(FollowersCount(Int32.Parse(matches[0].Value), Int32.Parse(matches[1].Value))); break;
You can simplify Int32.Parse by int.Parse (and that will allow to be consistant with the long.Parse above)

2022-09-07 14:33 UTC, marcogruhl commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
I like it, cause nothing can break and the error is somehow expressed to the user.

2022-09-07 14:51 UTC, marcogruhl commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
Ok. I think there are people who can do the whole ToExpression method with one line of regex ... but i am not that guy 😅

2022-09-07 19:46 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
Ahah, ranges were introduced with C# 8, it's not really REGEX
https://docs.microsoft.com/fr-fr/dotnet/api/system.range?view=net-6.0#remarks

2022-09-07 23:22 UTC, marcogruhl commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
> Ok. I think there are people who can do the whole ToExpression method with one line of regex ... but i am not that guy 😅

I meant this more general for the whole ToExpression method 😅

2022-09-07 23:22 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                    AddExpression(Expression.Cashtag(sr.Substring(1)));
Ah yeah, don't worry about it

2022-09-08 00:36 UTC, marcogruhl commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
had another idea. we do not parse the expression by default! (keep everything like before) So the user can decide to do so and is in charge to handle exceptions. nothing breaks, the feature stands alone, no potential performance impact on exceptions.

P.S.: i tried the try parse pattern and it doesnt really fit for the JsonConvert and would be very clunky.

2022-09-08 00:37 UTC, Xwilarg commented on src/JsonOption/ExpressionConverter.cs
> +                return new(reader.GetString(), "");
Ah yeah could be a good idea too

2022-09-08 22:47 UTC, marcogruhl commented
Im finished the changes, please look at it

2022-09-08 22:55 UTC, Xwilarg requested changes
Looks great! Just a bunch of small details and I think it'll be good

2022-09-08 22:55 UTC, Xwilarg commented on README.md
> +foreach (var rule in rules)
You can probably use .Count instead of doing a foreach

2022-09-08 22:55 UTC, Xwilarg commented on README.md
> +// get all the rules for FilteresStream
Could you capitalize the sentence to be consistent with the others comments?

2022-09-08 22:55 UTC, Xwilarg commented on README.md
> +await client.AddTweetStreamAsync(request); // Add them to the stream
This is a bit redundant with the previous example, maybe use a simpler one here or in the previous one or smth?

2022-09-08 22:55 UTC, Xwilarg commented on src/Rule/Expression.cs
> +            if(firstExpression != null && expressions is { Length: > 0 })
Small detail but can you please add an empty space between the if and parenthesis? (same for the else if)

2022-09-08 22:55 UTC, Xwilarg commented on src/Rule/Expression.cs
> +                    AddExpression(BoundingBox(coordinates[0],coordinates[1],coordinates[2],coordinates[3]));
Please add empty space after coma to be consistant with the previous lines (same for line 145)

2022-09-08 22:55 UTC, Xwilarg commented on src/Rule/Expression.cs
> +            var groups = new Dictionary<string[],bool>();
Space after coma

2022-09-08 23:01 UTC, marcogruhl commented on README.md
> +foreach (var rule in rules)
it would be this:
```CS
var authorCount = rules.Sum(rule => CountExpressionsOfType(Expression.Parse(rule.Value.ToString()), ExpressionType.Author));
```
ok?

2022-09-08 23:04 UTC, Xwilarg commented on README.md
> +foreach (var rule in rules)
Looks good but thinking of it, it doesn't offer that much so don't know if we should keep the foreach or not

2022-09-08 23:10 UTC, marcogruhl commented on README.md
> +foreach (var rule in rules)
I chose the foreach version because this part contains the main function of the example (`Expression.Parse`) and it also uses the helper function. squeeze this in one line wouldnt express the purpose ...

2022-09-08 23:11 UTC, Xwilarg commented on README.md
> +foreach (var rule in rules)
Yeah I agree, you can ignore this one

2022-09-08 23:17 UTC, marcogruhl commented on src/Rule/Expression.cs
> +            if(firstExpression != null && expressions is { Length: > 0 })
fixed it and all others

2022-09-08 23:18 UTC, Xwilarg commented on src/Rule/Expression.cs
> +            if(firstExpression != null && expressions is { Length: > 0 })
Be sure to press the "Resolve conversation" button when they are done so we can see the ones left

2022-09-08 23:20 UTC, marcogruhl commented on README.md
> +await client.AddTweetStreamAsync(request); // Add them to the stream
Maybe completely without the client request. Just build an expression ... so we can avoid the "extra" foreach

2022-09-08 23:21 UTC, Xwilarg commented on README.md
> +await client.AddTweetStreamAsync(request); // Add them to the stream
Sounds good

2022-09-09 00:02 UTC, marcogruhl commented
Done ...

2022-09-09 00:10 UTC, Xwilarg commented
I guess we have everything then, once again thanks a lot for your work! It's getting late rn so I'll probably update the NuGet version tomorrow

2022-09-09 00:10 UTC, Xwilarg approved these changes

2022-09-09 00:10 UTC, merged

2022-09-09 00:20 UTC, marcogruhl commented
> I guess we have everything then, once again thanks a lot for your work! It's getting late rn so I'll probably update the NuGet version tomorrow

thank you for your patience with my dirty code.

P.S. could you please build a new nuget pakage?

2022-09-09 00:27 UTC, Xwilarg commented
Yup I'll upload it tomorrow

2022-09-15 11:18 UTC, Xwilarg commented
I'm a bit late but I finally made the NuGet package:
https://www.nuget.org/packages/TwitterSharp/2.3.0