Add author_id to tweet.fields
Xwilarg/TwitterSharp pull request #41
Opened 2022-11-20 06:27 UTC by cryptisk-grs

This commit allows you to read the `author_id` from tweets by adding the new enum option `TweetOptions.Author_Id`

2022-11-20 15:21 UTC, Xwilarg commented
Looks good to me but would be nice if you could update the unit tests to cover that case

2022-11-21 12:48 UTC, marcogruhl reviewed
Looks like the special case is not necessary.

2022-11-21 12:48 UTC, marcogruhl commented on src/Request/Option/ASearchOptions.cs
> +                    if (x == TweetOption.Author_Id)
Is this necessary, when default x.ToString().ToLowerInvariant() ?

2023-01-12 00:24 UTC, marcogruhl commented
@cryptisk-grs are you still on that PR?

2023-01-12 00:31 UTC, marcogruhl requested changes
if (x == TweetOption.Author_Id) not needed
please add some test

2023-03-07 00:54 UTC, closed without merging