Add GetMe endpoint to TwitterClient
Xwilarg/TwitterSharp pull request #54
Opened 2023-03-04 14:18 UTC by jamescarter-le

TwitterClient was missing the /2/users/me endpoint as supported by Twitter API V2.

https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me

2023-03-04 21:23 UTC, marcogruhl commented
The Code is good. Test is missing BUT with our authentication method (bearer token) we can't request user context (for now). 
When i try this new endpoint i get an error: 
_Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context]._

I already added this working on a more generic [request logic](https://github.com/marcogruhl/TwitterSharp/tree/GeneralRequest) and hit that wall.

Does it work for you? Can you authenticate with user context?

2023-03-06 04:27 UTC, marcogruhl commented
> PS. As TwitterClient doesn't actually do anything with the RateLimit being returned (as far as I can see?) 

The RateLimit is returned by an event `public event EventHandler<RateLimit> RateLimitChanged;`

> I deal with this above TwitterClient, and so if we could set BearerToken outside the constructor, this would allow object pooling TwitterClients.

I dont understand. You must set the BearerToken from outside ...

PS: can you provide some code for OAuth2 authentication. I am half way there but still struggling with the token request.

2023-03-06 11:48 UTC, jamescarter-le commented
Hi Marco.

Yes I mean RateLimit is not used internally to throw a rate limit exception or back-off, or am I able to request the current Rate Limit for an Endpoint Group from TwitterClient - I do use RateLimitChanged to store these outside, but might be nice to have them available inside.

OK for Auth using OAuth 2 I do the following:

**Create a URI to direct the user for them to allow the passed Scopes to the App:**

```
        public string GetAuthenticationUri(Guid authKey)
        {
            var scopes = new List<string>
            {
                "tweet.read",
                "users.read",
                "follows.read",
                "like.read",
                "list.read",
                "offline.access"
            };
            var scopesText = string.Join("%20", scopes);
            var uri =
                $"https://twitter.com/i/oauth2/authorize?response_type=code&client_id={_options.ClientId}&redirect_uri={GetRedirectUri(authKey)}&scope={scopesText}&state=state&code_challenge=challenge&code_challenge_method=plain";
            return uri;
        }
```

**When the OAuth directs us back to the RedirectUri, you can swap the provided AuthCode for an AccessToken:**
(This is a portion of my method with some user stuff deleted)
Options ClientID and ClientSecret are the App/Project level settings from https://developer.twitter.com/en/portal/
```
         _httpClient = new HttpClient();
         var ourAuth = Convert.ToBase64String(Encoding.ASCII.GetBytes(_options.ClientId + ":" + _options.ClientSecret));
         _httpClient.DefaultRequestHeaders.Add("Authorization", "Basic " + ourAuth);

        public async Task<string> GetAccessTokenForAuthCode(int userId, string authCode)
        {
            try
            {
                await GetUsersSemaphore(userId).WaitAsync();
                
                ........

                var nvc = new List<KeyValuePair<string, string>>
                {
                    new("code", authCode),
                    new("grant_type", "authorization_code"),
                    new("client_id", _options.ClientId!),
                    new("redirect_uri", GetRedirectUri(user.TwitterChallengeKey!.Value)),
                    new("code_verifier", "challenge")
                };

                var response = await _httpClient.PostAsync("https://api.twitter.com/2/oauth2/token", new FormUrlEncodedContent(nvc));
                var responseString = await response.Content.ReadAsStringAsync();

                // Using the above auth to read from protected.
                OAuthGrant grant = JsonSerializer.Deserialize<OAuthGrant>(responseString);
                if (!string.IsNullOrEmpty(grant.Error))
                {
                    throw new TwitterAuthError(grant.Error);
                }

                user.TwitterAccessToken = grant.AccessToken;
                user.TwitterRefreshToken = grant.RefreshToken;
                user.TwitterAccessTokenExpiry = DateTime.UtcNow.AddSeconds(grant.ExpiresIn);

                var twitterClient = new TwitterClient(user.TwitterAccessToken);
                var me = await twitterClient.GetMeAsync();
                user.TwitterId = me.Id;
                user.TwitterUsername = me.Username;

                ......

            }
            finally
            {
                GetUsersSemaphore(userId).Release();
            }
        }
```

2023-03-06 12:18 UTC, marcogruhl commented
I should have asked earlier and save me some time 😅 Thank you! i will test the code this evening (CET)

RateLimit: there is no endpoint to request the current RateLimit or an other option to get it rather than with every request.
I work on a "version 3" of the api where i will return it also with every method. We decided historically to use the event to prevent breaking changes in the api.

2023-03-06 12:30 UTC, jamescarter-le commented
Yes currently I am taking Rate Limit and putting these in an ObjectCache because I share requests between different Twitter Users for some usecases:

```
                    var twitterClient = await _twitterFactory.GetForUser(userId);
                    twitterClient.RateLimitChanged += (sender, limit) =>
                    {
                        // Update the Rate Limit for this ApiUsers.
                        var key = $"{userId}_{limit.Endpoint}";
                        var expiry = DateTimeOffset.FromUnixTimeSeconds(limit.Reset);
                        _objectCache.Add(key, limit.Remaining, expiry);
                        
                        _logger.LogInformation("Rate Limit Changed, UserId: {userId}, Endpoint: {Endpoint}, Remaining: {Remaining}", userId, limit.Endpoint, limit.Remaining);
                    };
                    return (userId, twitterClient);
```

```
                var getUserRemaining = $"{userId}_{Endpoint.GetUserById}";
                var getFollowingsRemaining = $"{userId}_{Endpoint.GetFollowingsById}";
                var existingLimit = _objectCache.GetValues(
                    new [] { getUserRemaining, getFollowingsRemaining }
                );
```

Yes code is a little poor here, still working on this.

2023-03-07 00:53 UTC, marcogruhl requested changes
Because of a lack of an user-oauth2-method, user-scoped tests can't be done yet and its ok. maybe we find a workflow to do it!?
So just the rename and than i will approve it.

2023-03-07 00:53 UTC, marcogruhl commented on src/ApiEndpoint/Endpoint.cs
> +        [Endpoint(Resource = Resource.Users, EndpointType = EndpointType.GET, Url = "/2/users/me", Group = "Authenticated user", LimitPerUser = 75)]
Please change the group to "User lookup", cause resource and group are based on this list: [Products](https://developer.twitter.com/en/portal/products)

2023-03-08 23:03 UTC, marcogruhl approved these changes

2023-03-08 23:03 UTC, merged

2023-03-08 23:21 UTC, marcogruhl commented
PS: If you are interested, i could need some help with the "full implementation" of the endpoints. you can contact me over discord Grill#0729 or provide me how i can contact you ...